## Rules

exist = $(shell if [ -n `which pip` ]; then echo "myexists"; else echo "notexists"; fi;)

all:
#exist = $(shell if [ -n `which pip` ]; then echo "myexists"; else echo "notexists"; fi;)
ifeq ($(exist), notexists)
	  #wget https://bootstrap.pypa.io/get-pip.py; 
	$(warning "no pip")	
else
	$(warning "have pip")
endif
		

