#!/usr/bin/python
#=============================================================== 
# clay_uname 
#===============================================================
# @author : Zhiru Zhang
# @date   : 6/20/2015
# @brief  : A python script for extracting useful platform info.
#

import platform 
import optparse

#-------------------------------
# Define options
#-------------------------------

parser = optparse.OptionParser()

parser.add_option('-s', '--os', dest='os', action="store_true", 
                  default=False, help='System/OS info')
parser.add_option('-n', '--node', dest='node', action="store_true", 
                  default=False, help='Node info')
parser.add_option('-a', '--arch', dest='arch', action="store_true",
                  default=False, help='Architecture info')

#-------------------------------
# Parse options
#-------------------------------

(opts, args) = parser.parse_args()

# Get OS info
if opts.os :
  print platform.system()

# Get machine info
if opts.node :
  print platform.node()

# Get architecture info
if opts.arch :
  print platform.machine()
