# -*- MakeFile -*- 
#======================================================================
# Makefile.config
#======================================================================
# @author  : Zhiru Zhang
# @date    : April 4, 2017
# @brief   : Top-level makefile configs for DATuner. 
#
# BUILD_MODE : Release / Debug / Debug+Asserts
# DATuner_ROOT  : Root directory of the DATuner project
# DATuner_SRC   : Source directory of DATuner
# DATuner_OBJ   : Build directory of DATuner
# DATuner_PKG   : The directory that holds 3rd-party libraries & tools

# Release version
RELEASE_VERSION := 0.1

# Enable the following switch for an external release
#EXTERN_RELEASE := 1

#RELEASE_BUILD := 1
ifdef RELEASE_BUILD
  BUILD_MODE := Release
  ENABLE_OPTIMIZED := 1
  DISABLE_ASSERTIONS := 1
else
  ifndef DISABLE_ASSERTIONS
    BUILD_MODE := Debug+Asserts
  else
    BUILD_MODE := Debug
  endif
endif

# Specify current directory level with respect to DATuner_ROOT
ifndef LEVEL
  LEVEL := .
endif

# Important DATuner directories
ifndef DATuner_ROOT
  CurrDir = $(shell pwd)
  DATuner_ROOT = $(shell cd $(CurrDir)/$(LEVEL); pwd)
endif
DATuner_SRC = $(DATuner_ROOT)/src
DATuner_SCRIPT = $(DATuner_ROOT)/scripts
DATuner_OBJ = $(DATuner_ROOT)/build/obj-$(OS)-$(ARCH)-$(CXX)
DATuner_PKG = $(DATuner_ROOT)/pkgs
DATuner_PKG_BUILD = $(DATuner_ROOT)/build/pkgs
DATuner_PKG_INSTALL = $(DATuner_PKG_BUILD)/install
DATuner_PKG_PYTHON_INSTALL = $(DATuner_PKG_BUILD)/python/install
# Release the platform information
OS = $(shell $(DATuner_ROOT)/DATuner_uname -s)
MACHINE = $(shell $(DATuner_ROOT)/DATuner_uname -n)
ARCH = $(shell $(DATuner_ROOT)/DATuner_uname -a)

# Compiler settings
CXX := g++
CC := gcc

# Specify verbose message setting
# VERBOSE := 1
ifdef VERBOSE
  Verb=
else
  Verb=@
endif
Echo=echo

# Misc settings
MKDIR := mkdir -p

# Settings Build date
DATE := date
BUILD_DATE_FILE = $(DATuner_ROOT)/$(BUILD_MODE)/DATE


