# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: hecmay/demo:v3

    working_directory: ~/datuner

    steps:
      - checkout

#      - restore_cache:
#          key: v1-datuner-{{ checksum "Makefile" }}-{{ checksum "Makefile.config" }}
#

      - run: make

      - run: 
          name: set environment variable
          command: |
            source ./setup.sh
            whoami

      - run: which python

      - run: python auto_test.py

#      - save_cache:
#          paths:
#            - build
#          key: v1-datuner-{{ checksum "Makefile" }}-{{ checksum "Makefile.config" }}
        
      # run tests
