#
# Indicates our relative path to the top of the project's root directory.
#
SRC_LEVEL = .
DIRS = include src

#
# Include the Master Makefile that knows how to build all.
#
include $(SRC_LEVEL)/Makefile.common
