EXE_OUT = DATuner_master

Master_SRC = controller.cpp bandit.cpp space_generator.cpp msg_passing.cpp space_partition.cpp stopwatch.cpp


Master_OBJ = $(Master_SRC:%.cpp=$(MY_TOOL_BUILD)/%.o)
Master_DEP = $(patsubst %,%.d,$(basename $(Master_OBJ)))

all :: $(MY_TOOL_BIN)/$(EXE_OUT)

$(EXE_OUT) :: $(Master_OBJ)
	$(MY_TOOL_CC) -o $(MY_TOOL_BIN)/$(EXE_OUT) $^ $(LDFLAGS)

$(MY_TOOL_BIN)/$(EXE_OUT) :: $(Master_OBJ)
	$(MY_TOOL_CC) -o $@ $^ $(LDFLAGS)

clean ::
	rm -f $(Master_DEP)
	rm -f $(Master_OBJ)
	rm -f $(MY_TOOL_BIN)/$(EXE_OUT)

-include $(Master_DEP)
